### ISSUE TITLE
idで使える文字を制限する

### ISSUE THREAD

**Issue by h-takesg** [kusumotolab/kJuiceApp#49]
記号を含むidは問題になりがち
実際idにセミコロンが入っていると削除や更新ができなくなる
これはidを直接endpointに使っている関係上backendがidを一続きの文字列と認識できなくなるため

[ここ](https://www.asahi-net.or.jp/~ax2s-kmtn/ref/uric.html#:~:text=%E3%81%BE%E3%81%A8%E3%82%81%E3%82%8B%E3%81%A8%E3%80%81URI%E3%81%AB%E8%87%AA%E7%94%B1%E3%81%8B%E3%81%A4%E5%AE%89%E5%85%A8%E3%81%AB%E4%BD%BF%E7%94%A8%E3%81%A7%E3%81%8D%E3%82%8B%E6%96%87%E5%AD%97%E3%81%AF%E3%80%81%E6%AC%A1%E3%81%AE%E3%81%A8%E3%81%8A%E3%82%8A%E3%81%A7%E3%81%99%E3%80%82)を参考に

> * ラテン小文字(小文字アルファベット)： a～z
> * 数字： 0～9
> * ハイフンマイナス： -
> * アンダーライン： _

に制限する

`^[a-z0-9_-]+$` にマッチする文字列のみIDとして受け入れればよい

**Comment by grtw2116** [comment]
frontとbackの両方でバリデーションする
