### ISSUE TITLE
testがflaky

### ISSUE THREAD

**Issue by kusumoto-lab** [kusumotolab/kJuiceApp#74]
一度に全テスト実行すると落ちるテストがある
一方で一つ一つ実行すると全て通る

原因はテスト間のデータベース初期化が失敗しているため
DBRiderの使い方に問題がありそう
要調査

**Comment by h-takesg** [comment]
# 問題
`billServiceTest`クラスのテスト間でデータベースの初期化が走っていない．
よって個別実行か否かで結果が変わる．

# 考察
Test毎に`cleanAfter = True`をつけるとテストが通った．
テストクラスに対する`@DataSet(cleanBefore = true)`が効いていない？
メソッド単位で付与する必要あり？

一方でDatabaseRiderの[公式ドキュメント](https://database-rider.github.io/database-rider/latest/documentation.html#:~:text=%40DataSet(cleanBefore%20%3D%20true)%0Apublic%20class%20DBUnitJUnit5It%20%7B)でもクラスに`@DataSet(cleanBefore = true)`をつけている．
また，同じ書き方をしているController系のテストでTest毎の初期化が走っていることと矛盾する．
わからん

# 修正
単純に直すだけなら
ここを
https://github.com/kusumotolab/kJuiceApp/blob/c86d3b784d3bf3d79d540806097055a21de32f1f/backend/src/test/java/jp/ac/osaka_u/ist/sdl/kjuiceapp/service/BillServiceTest.java#L34
こう
```
@DataSet(value = "BillService/makeInvoiceMessage/before.yaml", cleanAfter = true) 
```
でよい
